// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ielndcrhhhzkjikpblfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllbG5kY3JoaGh6a2ppa3BibGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTg2MzEsImV4cCI6MjA2MjI3NDYzMX0.uLNIhGyL2IISIbzV1XcEl1REba8O5Z8Ksnn7kuBXrrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);